#%RAML 1.0 DataType
type: object
properties:
  orderId: string
  deliveryAddress: string
  totalPrice: integer
  orderStatus: string
  customerName: string
  restaurantName: string
  restaurantAddress: string
  orderItems:
    type: array
    items: !include OrderItemDetails.raml

      